Serilog:
    Using: [ "Serilog.Sinks.Console" ]
    MinimumLevel:
        Default: Information
        Override:
            SS14: Debug
            Microsoft: "Warning"
            Microsoft.Hosting.Lifetime: "Information"
            Microsoft.AspNetCore: Warning
            IdentityServer4: Warning
    WriteTo:
        - Name: Console
          Args:
              OutputTemplate: "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}"

    Enrich: [ "FromLogContext" ]

    #Loki:
    #    Address: "http://localhost:3102"
    #    Name: "centcomm"

ConnectionStrings:
    # Connects to the same postgres database as the game server
    DefaultConnection: "Server=database;Port=5432;Database=ss14;User Id=ss14-user;Password=5Hvbvhxm3Qoaqi7b"

AllowedHosts: "*"

urls: "http://10.5.0.3:27689/"

PathBase: "/admin"

WebRootPath: "/opt/ss14_admin/bin/wwwroot"

ForwardProxies:
    - 10.5.0.6
    - 10.5.0.1

Auth:
    Authority: "https://central.spacestation14.io/web/"
    ClientId: "259ce3b1-4229-4a52-956d-f8730ea8e961"
    ClientSecret: "Ug0bvXbdVqWZ/p3YPwfC5ocA6xGhaD2WzIgOo//kIFK0QDCz"

authServer: "https://central.spacestation14.io/auth"